<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EFM9JGP" failures="5" tests="9" name="Testing" time="8.21" errors="0" timestamp="2020-06-26T01:49:59 IST">
  <testcase classname="restServices.LibraryServicesSingleTest" name="restTest_TS" time="4.664">
    <failure type="java.lang.AssertionError" message="expected [FINISHED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [FINISHED] but found [FAILED]
at restServices.LibraryServicesSingleTest.restTest_TS(LibraryServicesSingleTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restTest_TS -->
  <testcase classname="soapServices.EmployeeServicesSingleTest" name="SoapTest_TS" time="2.013"/>
  <testcase classname="restServices.LibraryServicesMultipleTest" name="SoapTest_TS1" time="0.134">
    <failure type="java.lang.AssertionError" message="expected [FINISHED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [FINISHED] but found [FAILED]
at restServices.LibraryServicesMultipleTest.SoapTest_TS1(LibraryServicesMultipleTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- SoapTest_TS1 -->
  <testcase classname="restServices.LibraryServicesMultipleTest" name="restTest_TS2" time="0.141">
    <failure type="java.lang.AssertionError" message="expected [FINISHED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [FINISHED] but found [FAILED]
at restServices.LibraryServicesMultipleTest.restTest_TS2(LibraryServicesMultipleTest.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restTest_TS2 -->
  <testcase classname="restServices.LibraryServicesMultipleTest" name="restTest_TS3" time="0.081">
    <failure type="java.lang.AssertionError" message="expected [FINISHED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [FINISHED] but found [FAILED]
at restServices.LibraryServicesMultipleTest.restTest_TS3(LibraryServicesMultipleTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restTest_TS3 -->
  <testcase classname="restServices.LibraryServicesMultipleTest" name="restTest_tS4" time="0.121">
    <failure type="java.lang.AssertionError" message="expected [FINISHED] but found [FAILED]">
      <![CDATA[java.lang.AssertionError: expected [FINISHED] but found [FAILED]
at restServices.LibraryServicesMultipleTest.restTest_tS4(LibraryServicesMultipleTest.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- restTest_tS4 -->
  <testcase classname="soapServices.EmployeeServicesMultipleTest" name="SoapTest_TS1" time="0.324"/>
  <testcase classname="soapServices.EmployeeServicesMultipleTest" name="SoapTest_TS2" time="0.454"/>
  <testcase classname="soapServices.EmployeeServicesMultipleTest" name="SoapTest_TS3" time="0.196"/>
</testsuite> <!-- Testing -->
